## Iris Classification using K-Fold Cross Validation

K-Fold Cross Validation is done on the iris flower dataset to find which Model is the best fitting model.

### Gathering dataset and importing necessary modules

In [1]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
import warnings
warnings.filterwarnings('ignore')

In [2]:
iris=load_iris()

### Cross Vaidation is done and score is computed for comparison

### Logistic Regression

In [3]:
lr_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
lr_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [4]:
np.average(lr_scores)

0.9733333333333334

### SVC

In [8]:
svm_scores = cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [9]:
np.average(svm_scores)

0.9666666666666666

### Random Forest Classifier

In [10]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [11]:
np.average(rf_scores)

0.9533333333333334

### Decision Tree Classifier

In [12]:
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [13]:
np.average(dt_scores)

0.9666666666666668

### Conclusion

We can conclude that Logistic Regression gives more accuracy and hence, does better classification on Iris flower dataset.